USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS DEV_DB;
CREATE SCHEMA IF NOT EXISTS DEV_DB.DBT_LEARNING;

GRANT USAGE ON DATABASE DEV_DB TO ROLE SVC_SAMPLE_ROLE;
GRANT USAGE ON SCHEMA DEV_DB.DBT_LEARNING TO ROLE SVC_SAMPLE_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FUNCTION, CREATE PROCEDURE
  ON SCHEMA DEV_DB.DBT_LEARNING TO ROLE SVC_SAMPLE_ROLE;

USE DATABASE DEV_DB;
USE SCHEMA DBT_LEARNING;


CREATE DATABASE IF NOT EXISTS PROD_DB;
CREATE SCHEMA IF NOT EXISTS PROD_DB.DBT_LEARNING;

CREATE SCHEMA IF NOT EXISTS PROD_DB.DBT_LEARNING;

CREATE OR REPLACE TABLE PROD_DB.DBT_LEARNING.STG_CUSTOMERS AS
SELECT * FROM DEV_DB.DBT_LEARNING.STG_CUSTOMERS;

CREATE OR REPLACE TABLE PROD_DB.DBT_LEARNING.STG_ORDERS AS
SELECT * FROM DEV_DB.DBT_LEARNING.STG_ORDERS;

CREATE OR REPLACE TABLE PROD_DB.DBT_LEARNING.STG_LINEITEMS AS
SELECT * FROM DEV_DB.DBT_LEARNING.STG_LINEITEMS;

-- for dev db
GRANT ALL PRIVILEGES ON DATABASE DEV_DB TO ROLE SVC_SAMPLE_ROLE;

-- very likely you’ll want the same for prod db
GRANT ALL PRIVILEGES ON DATABASE PROD_DB TO ROLE SVC_SAMPLE_ROLE;


UPDATE PROD_DB.DBT_LEARNING.STG_CUSTOMERS
SET CUSTOMER_NAME='111'
WHERE CUSTOMER_KEY='134973';

SELECT * FROM PROD_DB.DBT_LEARNING.STG_CUSTOMERS
WHERE CUSTOMER_KEY='134973';


--CORTEX DATA DIFF
CREATE SCHEMA IF NOT EXISTS DEV_DB.Data_diff_DBT_LEARNING;

CREATE OR REPLACE TABLE DEV_DB.Data_diff_DBT_LEARNING.Data_diff_STG_CUSTOMERS AS
SELECT * FROM DEV_DB.DBT_LEARNING.STG_CUSTOMERS;

CREATE SCHEMA IF NOT EXISTS PROD_DB.Data_diff_DBT_LEARNING;

CREATE OR REPLACE TABLE PROD_DB.Data_diff_DBT_LEARNING.Data_diff_STG_CUSTOMERS AS
SELECT * FROM DEV_DB.DBT_LEARNING.STG_CUSTOMERS;

SELECT TOP 10 * FROM DEV_DB.Data_diff_DBT_LEARNING.Data_diff_STG_CUSTOMERS;

CREATE DATABASE IF NOT EXISTS TEST_DB;
CREATE SCHEMA IF NOT EXISTS TEST_DB.Data_diff_DBT_LEARNING;

CREATE OR REPLACE TABLE TEST_DB.Data_diff_DBT_LEARNING.Data_diff_STG_CUSTOMERS AS
SELECT * FROM DEV_DB.DBT_LEARNING.STG_CUSTOMERS;

CREATE DATABASE IF NOT EXISTS TEST1_DB;
CREATE SCHEMA IF NOT EXISTS TEST1_DB.Data_diff_DBT_LEARNING;

CREATE OR REPLACE TABLE TEST1_DB.Data_diff_DBT_LEARNING.Data_diff_STG_CUSTOMERS AS
SELECT * FROM DEV_DB.DBT_LEARNING.STG_CUSTOMERS;

